[project]
name = "wholesale-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.120.0",
    "python-dotenv>=1.2.0",
    "uvicorn>=0.38.0",
]
